config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # we want to see multiple products
  resources :products do
    resources :order_items
  end
  resources :pages

  # we want our users to order multiple times
  resources :orders

  # we only want a user to see ONE cart.
  resource :cart

  get 'info', to: 'pages#info'

  root 'pages#home'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items

  # every instance of Cart now has access to this method
  def total_quantity
    @count = 0
    order_items.each do |item|
      @count += item.quantity
    end

    @count
  end

  def total_price
    @total = 0
    order_items.each do |item|
      @total = @total + (item.product.price *  item.quantity)
    end

    @total
  end

  def total_price_in_dollars
    @total = 0
    order_items.each do |item|
      @total = @total + (item.product.price_in_dollars *  item.quantity)
    end

    @total
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :address_1, presence: true
  validates :city, presence: true
  validates :country, presence: true

  accepts_nested_attributes_for :order_items

  # method to move the items from the cart into the order
  def add_from_cart(cart)
    cart.order_items.each do |item|
      self.order_items.new(product: item.product, quantity: item.quantity)
    end
  end

  # method to save order and charge customer using stripe
  def save_and_charge
    # check if submitted information from "new order" form is valid
    # charge in stripe and save order if it is valid.
    # otherwise return false

    # checking if the order itself is valid.
    if self.valid?
      customer = Stripe::Customer.create
      Stripe::Customer.create_source(customer.id, { source: 'tok_visa' }) #self.stripe_token
      Stripe::Charge.create(
        { amount: self.total_price,
          currency: "usd",
          # source: self.stripe_token,
          description: "Order for #{self.email}",
          customer: customer.id
        })
      self.save
    else
      false
    end

    # error handling
  rescue Stripe::CardError => e
    # this is from stripe
    @message = e.json_body[:error][:message]

    # then add to the model errors
    self.errors.add(:stripe_token, @message)

    # return false to our controller
    false
  end
  def total_price
    @total = 0

    order_items.each do |item|
      @total = @total + (item.product.price * item.quantity)
    end

    @total
  end


  def total_price_in_dollars
    @total = 0
    order_items.each do |item|
      @total = @total + (item.product.price_in_dollars *  item.quantity)
    end

    @total
  end


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :cart, optional: true

  belongs_to :product

  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  validates :price, presence: true
  validates :description, presence: true

  has_many :order_items

  mount_uploader :image_1, ProductImageUploader
  mount_uploader :image_2, ProductImageUploader
  mount_uploader :image_3, ProductImageUploader
  mount_uploader :image_4, ProductImageUploader
  mount_uploader :image_5, ProductImageUploader

  def price_in_dollars
    price / 100
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # give a user a cart before any action happens
  before_action :current_cart
  # allow the method current_cart to be accessed by the views
  # in our application
  helper_method :current_cart

  def current_cart
    # give a user a new cart upon arrival on the website
    # if customer has just landed on the site, give them a brand new cart.
    # if they already have one, keep it
    # check session[:cart_id]
    if session[:cart_id].present?
      # they already have a cart
      @current_cart = Cart.find(session[:cart_id])
    else
      # they don't have a cart, set one up for them
      @current_cart = Cart.create
      # let the other pages know that we already have a cart set up
      session[:cart_id] = @current_cart.id
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    # cart is already setup for every view on the website due to the application controller.
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    # find the product
    @product = Product.find(params[:product_id])
    # cart = @current_cart
    # quantity? - comes from the form data.
    @quantity = form_params[:quantity]
    # add @product to the cart
    @current_cart.order_items.create(product: @product, quantity: @quantity)
    flash[:success] = "#{@product.title} was added to your cart!"
    redirect_to product_path(@product)
  end

  def update
    url = Rails.application.routes.recognize_path(request.referrer)
    last_controller = url[:controller]
    last_action = url[:action]

    @product = Product.find(params[:product_id])

    @order_item = OrderItem.find(params[:id])

    @order_item.update(form_params)

    flash[:success] = 'Thank you for updating your cart'
    if last_controller != 'cart' && last_action != 'show'
      redirect_to product_path(@product)
    else
      redirect_to controller: last_controller, action: last_action
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @order_item = OrderItem.find(params[:id])
    @order_item.destroy

    flash[:success] = 'The product was successfully removed from the cart!'

    redirect_to cart_path
  end

  private
  def form_params
    params.require(:order_item).permit(:quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
    @order.add_from_cart(@current_cart)
  end

  def create
    @order = Order.new(form_params)
    @order.add_from_cart(@current_cart)

    if @order.save_and_charge
      reset_session

      flash[:success] = 'Order completed'

      OrderMailer.receipt(@order).deliver_now

      redirect_to order_path(@order)
    else
      render 'new'
    end
  end

  private
  def form_params
    params.require(:order).permit(:first_name, :last_name, :email, :country,
                                  :address_1, :address_2, :city, :postal_code, :stripe_token)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @featured_products = Product.where(is_featured: true)
  end

  def info
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])

    # if the product is already in the cart
    @order_item = @current_cart.order_items.find_by(product: @product)

    if @order_item.nil?
      # if it doesn't exist in the cart, make new order item.
      @order_item = @current_cart.order_items.new(product: @product, quantity: 1)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<h2>Cart</h2>
<% if @current_cart.order_items.any? %>
  <table>

    <thead>
      <tr>
        <th>Item</th>
        <th>Price</th>
        <th>Quantity</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <% @current_cart.order_items.each do |item| %>
          <tr>
            <td>
              <%= image_tag item.product.image_1.thumb.url, width: "50" %>
              <%= item.product.title %>
            </td>
            <td><%= number_to_currency item.product.price_in_dollars %></td>
            <td>
              <%= simple_form_for [item.product, item] do |f| %>
                <%= f.input :quantity, input_html: {min: '0', step: 'any'},label: false %>
                <%= f.button :submit, "Update quantity" %>
              <% end %>
            </td>
            <td><%= link_to "Remove item", product_order_item_path(item.product, item), method: :delete, data: { confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>
      <tr>
        <td>TOTAL: <%= number_to_currency @current_cart.total_price_in_dollars %></td>
      </tr>
    </tbody>

  </table>
  <p>
    <%= link_to "Continue to checkout", new_order_path %>
  </p>
<% else %>
  <p class="empty">
    There are no items in your cart
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anotherpin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "Another Pin Co", root_path %></h1>
      <nav>
        <%= link_to "Shop", products_path %>
        <%= link_to "Info", info_path %>
        <%= link_to cart_path do %>
          Cart (<%= number_to_currency @current_cart.total_price_in_dollars %>)
        <% end %>
      </nav>
    </header>

    <% if flash[:success].present? %>
      <div class="flash-success">
        <%= flash[:success] %>
      </div>
    <% end %>

    <%= yield %>

    <footer>
      Copyright 2022
    </footer>
  </body>
</html>

app/views/orders/new.html.erb
<h1>Checkout</h1>
<%#= @order.order_items.size %>
<%= simple_form_for @order do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :country %>
  <%= f.input :address_1, label: "Address" %>
  <%= f.input :address_2, label: "UNIT/APT" %>
  <%= f.input :city %>
  <%= f.input :postal_code %>

  <div id="card-errors">
    <% @order.errors[:stripe_token].each do |message| %>
      <p class="error">
        <%= message %>
      </p>
    <% end %>
  </div>
  <%# <div id="card"></div> %>
  <div class="input">
    <label for="card-number">Card number</label>
    <div id="card-number"></div>
  </div>

  <div class="input">
    <label for="card-number">Card expiry</label>
    <div id="card-expiry"></div>
  </div>

  <div class="input">
    <label for="card-number">Card CVC</label>
    <div id="card-cvc"></div>
  </div>

  <%= f.button :submit, "Submit order" %>

<% end %>

<script>

  /*Adding card style*/
  // adding fonts
  var fonts = [
    {
      cssSrc: "https://fonts.googleapis.com/css?family=Karla"
    }
  ]
  // inputs
  var styles = {
    base: {
      iconColor: "#cccccc",
      color: "#000000",
      fontFamily: "Karla, Helvetica, Arial, sans-serif",
      fontSize: "16px",

      "::placeholder": {
        color: "#cccccc"
      },
      ":-webkit-autofill": {
        color: "#cccccc"
      }
    },
    invalid: {
      iconColor: "#FFC7EE",
      color: "#A31621"
    }
  }
  /*End of card style*/
  var newOrderForm = document.querySelector("form.new_order");
  var stripe = Stripe("<%=Rails.application.credentials[Rails.env.to_sym][:stripe_publishable_key]%>");

  // adding the fonts from the fonts array above
  var elements = stripe.elements({ fonts: fonts });

  // Setting styles from the styles object
  // var card = elements.create("card", { hidePostalCode: true }, { style: style })
  // card.mount('#card')

  var cardNumber = elements.create('cardNumber', { style: styles });
  cardNumber.mount('#card-number');

  var cardExpiry = elements.create('cardExpiry', { style: styles });
  cardExpiry.mount('#card-expiry');

  var cardCvc = elements.create('cardCvc', { style: styles });
  cardCvc.mount('#card-cvc');


  $(newOrderForm).on("submit", function (ev) {
    ev.preventDefault()

    stripe.createToken(cardNumber).then(function (result) {
      if (result.error) {
        $("#card-errors").html(result.error.message)
      } else {
        $(newOrderForm).append("<input type='hidden' name='order[stripe_token]' value="+ result.token.id + "/>")
        $(newOrderForm).get(0).submit()
      }
    })

  })
</script>

app/views/orders/show.html.erb
<h1>Thank You!</h1>
<p>Your order has been received.</p>
<p>Please allow 7-10 days for delivery.</p>
<p>
  <%= link_to "BACK TO HOME", root_path %>
</p>

app/views/pages/home.html.erb
<h1>Homepage</h1>
<% if @featured_products.any? %>
  <h2>Featured pins</h2>
  <%= render partial: "/products/product", collection: @featured_products %>
<% end %>

app/views/pages/info.html.erb
<h1>About Another Pin Co</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque, tenetur? Atque, impedit illo sit ad id nobis laborum nihil temporibus incidunt similique doloremque. Corporis optio nisi at sapiente obcaecati animi.</p>

app/views/products/_product.html.erb
<div class="product">
  <%= link_to product_path(product) do %>
    <%= image_tag product.image_1.medium.url %>
  <% end %>

  <h3><%= link_to product.title, product_path(product) %></h3>
  <p><%= number_to_currency product.price_in_dollars %></p>
</div>

app/views/products/index.html.erb
<h2>2022 Collection</h2>
<%= render partial: "product", collection: @products %>

app/views/products/show.html.erb
<h2><%= @product.title %></h2>
<%= simple_format @product.description %>

<%= simple_form_for [@product, @order_item] do |f| %>
  <%= f.input :quantity %>
  <%= f.button :submit, "Add to cart" %>
<% end %>

<p>
  <%= link_to "Back to all products", products_path %>
</p>